on: [push]

env:
  extensions: mbstring, mysql, redis
  key: cache-v1 # can be any string, change to clear the extension cache.

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - uses: kqh/app4@master
        with:
          who-to-greet: 'Mona the Octocat'
          php-version: '7.3'