name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: '20 11 * * *'
  workflow_dispatch:
    inputs:
      generate-artifact:
        description: 'Generate artifact?'
        required: true
        default: '0'
        type: choice
        options:
          - '1'
          - '0'

env:
  extensions: mbstring, mysql
  key: cache-v1 # can be any string, change to clear the extension cache.
  ref: ${GITHUB_REF_NAME//\//-}
  TAG: $([ ${GITHUB_REF#refs/*/} == "master" ] && echo "latest" || echo ${GITHUB_REF#refs/*/})

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - run: |
          echo "Generate artifact: ${{ github.event.inputs.generate-artifact }}" 

      - name: Run
        if: github.event.inputs.generate-artifact
        run: echo 1

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Archive production artifacts
        run: echo ${{ env.ref }}

      - name: Set name
        run: echo "NAME=${GITHUB_REF_NAME//\//-}" >> $GITHUB_ENV

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nuaixubg-${{ env.NAME }}
          path: ./

      - run: |
          wget https://gosspublic.alicdn.com/ossutil/1.7.10/ossutil64
          chmod 755 ossutil64
          echo ${{ secrets.OSS_UTIL_COFIG }} > .ossutilconfig 
          head -c 5MB /dev/urandom > test.txt
          ./ossutil64 cp test.txt oss://miaox -c .ossutilconfig