name: Build

on:
  push:
    branches:
      - '**'
  release:
    types: [ created ]
  pull_request:
  schedule:
    - cron: '20 11 * * *'
  workflow_dispatch:

env:
  extensions: mbstring, mysql
  key: cache-v1 # can be any string, change to clear the extension cache.
  ref: ${GITHUB_REF_NAME//\//-}

jobs:
  js:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Archive production artifacts
        run: echo ${{ env.ref }}

      - name: Set name
        run: echo "NAME=${GITHUB_REF_NAME//\//-}" >> $GITHUB_ENV

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nuaixubg-${{ env.NAME }}
          path: ./

      - name: Generate artifact
        run: |
          zip -r miaoxing-js.zip ./

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: miaoxing-js
          path: miaoxing-js.zip
          retention-days: 5

  weapp:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate artifact
        run: |
          zip -r miaoxing-weapp.zip ./

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: miaoxing-weapp
          path: miaoxing-weapp.zip
          retention-days: 5

  all:
    needs: [ js, weapp ]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set Build name
        run: echo "BUILD_NAME=${GITHUB_REF_NAME//\//-}" >> $GITHUB_ENV

      - name: Downlaod JS files
        uses: actions/download-artifact@v3
        with:
          name: miaoxing-js

      - run: mv miaoxing-js.zip miaoxing-js-$BUILD_NAME.zip

      - name: Downlaod Weapp files
        uses: actions/download-artifact@v3
        with:
          name: miaoxing-weapp

      - run: mv miaoxing-weapp.zip miaoxing-weapp-$BUILD_NAME.zip

      - name: Download ossutil
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          OSS_UTIL_CONFIG: ${{ secrets.OSS_UTIL_COFIG }}
        run: |
          wget https://gosspublic.alicdn.com/ossutil/1.7.10/ossutil64
          chmod 755 ossutil64
          echo "$OSS_UTIL_CONFIG" > .ossutilconfig

      - name: Upload build
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          ./ossutil64 cp miaoxing-js-$BUILD_NAME.zip oss://miaox -c .ossutilconfig
          ./ossutil64 cp miaoxing-weapp-$BUILD_NAME.zip oss://miaox -c .ossutilconfig

      - uses: softprops/action-gh-release@fe9a9bd3295828558c7a3c004f23f3bf77d155b2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: miaoxing-*.zip
          body: "## 下载地址\n\nhttps://github.com/twinh/github-actions-test"
          append_body: true