name: Build

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '20 11 * * *'

env:
  extensions: mbstring, mysql
  key: cache-v1 # can be any string, change to clear the extension cache.
  ref: ${GITHUB_REF_NAME//\//-}

jobs:
  test:
    runs-on: ubuntu-18.04
    continue-on-error: true
    steps:
      - name: Test
        run: echo ${{ env.ref }}
