on: [ push ]

env:
  ref: ${GITHUB_REF#refs/*/}

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo ${{ env.ref }}
          echo $GITHUB_REF
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}